import { Question } from './Question';
import * as uuid from 'uuid';
import { attribute, table, autoGeneratedHashKey } from '@aws/dynamodb-data-mapper-annotations';

@table('placeyourbets_games')
export class Game {

    @autoGeneratedHashKey()
    id: string;

    @attribute()
    lastUpdated: string;

    @attribute()
    currentQuestion: Question;

    @attribute()
    questionNumber: number;

    @attribute()
    totalQuestions: number;

    @attribute()
    score: number;

    @attribute()
    status: GameStatus;

    setupNewGame() {
        this.id = uuid.v4();
        this.totalQuestions = 12;
        this.questionNumber = 0;
        this.score = 1000;
        this.status = GameStatus.Start;
    }
}

export enum GameStatus {
    Start = 'START',
    Category = 'CATEGORY',
    Question = 'QUESTION',
    Answered = 'ANSWERED',
    End = 'END'
}